# Generated by Django 3.0.6 on 2020-05-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='books',
            field=models.CharField(default='Программирование на Python', max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='devlang',
            field=models.CharField(default='Python', max_length=64),
        ),
    ]
